Happ 445 write unit tests for coredata functionality
bcgov/myhealthBC-iOS pull request #157
Opened 2022-01-28 16:33 UTC by freshfawzy

Created core data stack class for test, and wrote test cases for Patient and VaccineCard entities

2022-02-01 17:57 UTC, ConnorOgilvie91 commented on BCVaccineCard/BCVaccineCard/Screens/ReusableViewControllers/GatewayFormViewController.swift
> +        guard let phn = self.personalHealthNumber() else { return }
the id returned from func handleTestResultInCoreData is not the PHN, can you please revert this change

2022-02-01 17:59 UTC, ConnorOgilvie91 commented on BCVaccineCard/BCVaccineCard/Screens/ReusableViewControllers/GatewayFormViewController.swift
> +    func personalHealthNumber() -> String? {
These two aren't the same - the logic should not be stripped out of handleTestResultInCoreData

2022-02-01 18:00 UTC, ConnorOgilvie91 commented on BCVaccineCard/BCVaccineCard/Screens/ReusableViewControllers/GatewayFormViewController.swift
> +    func handleTestResultInCoreData(gatewayResponse: GatewayTestResultResponse, authenticated: Bool, phn: String, birthday: Date?) -> String? {
This looks like it's no longer being used - can you revert the changes on this file? These changes will cause the functionality to not work on prod

2022-02-02 20:31 UTC, AmirShayegh requested changes

2022-02-02 20:37 UTC, AmirShayegh requested changes

2022-02-02 20:37 UTC, AmirShayegh commented on BCVaccineCard/BCVaccineCard/CoreDataStack.swift
> +extension CoreDataStackProtocol {
Also why is this a protocol and not a struct or class?

2022-02-03 14:20 UTC, freshfawzy commented on BCVaccineCard/BCVaccineCard/CoreDataStack.swift
> +extension CoreDataStackProtocol {
just to have a class with single responsibility (CoreDataStack) which is responsible for creating the persistent container and managed object context used by StorageService

2022-02-07 17:15 UTC, AmirShayegh approved these changes

2022-02-08 10:10 UTC, merged